---
version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  groups:
    patch:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "patch"

- package-ecosystem: composer
  directory: /
  schedule:
    interval: daily
  groups:
    patch:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "patch"
