---
exclude: .*csv
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  #- id: check-yaml
  - id: check-byte-order-marker
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-builtin-literals
  - id: debug-statements
  - id: requirements-txt-fixer
  - id: fix-encoding-pragma
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.8
  hooks:
  - id: bandit
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
- repo: https://github.com/digitalpulp/pre-commit-php
  rev: 1.4.0
  hooks:
  - id: php-lint-all
  - id: php-lint
  - id: php-unit
  # - id: php-cs
  - id: php-cbf
  - id: php-cs-fixer
  - id: php-stan
